name: Tests
on:
  workflow_dispatch: {}
  push:
    paths-ignore:
      - '**.md'
      - '!ATTRIBUTION.md'
      - '.gitignore'
      - '.gitattributes'
      - '.github/workflows/godot-cd-export.yml'

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-tests
  cancel-in-progress: true

env:
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  test:
    name: 'gdUnit4 Tests'
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
    steps:
      # checkout your repository
      - uses: actions/checkout@v4
      # run tests by using the gdUnit4-action with Godot version 4.x and the latest GdUnit4 release

      - name: "Run Tests"
        uses: MikeSchulze/gdUnit4-action@v1.1.6
        with:
          godot-version: '4.5'
          paths: 'res://test/'
          timeout: 5
          report-name: test_report.xml
          arguments: '--verbose'

      - name: "Upload Unit Test Reports"
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          path: |
            reports/**
            /var/lib/systemd/coredump/**
            /var/log/syslog
