name: Deploy
on:
  workflow_dispatch:
    inputs:
      exporttype:
        description: Export type (debug/release)
        default: debug
        required: false
        type: choice
        options:
          - debug
          - release
  push:
    paths-ignore:
      - '**.md'
      - '!ATTRIBUTION.md'
      - '.gitignore'
      - '.gitattributes'

concurrency:
  group: there-can-be-only-one-export
  cancel-in-progress: true

env:
  GODOT_VERSION: 4.5
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  export:
    name: Export
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Godot files
        id: cache-godot
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/godot/**
            /usr/local/bin/godot
          key: ${{ runner.os }}-godot-${{ env.GODOT_VERSION }}

      - name: Setup Godot
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          curl -LO https://github.com/godotengine/godot/releases/download/$GODOT_VERSION-stable/Godot_v$GODOT_VERSION-stable_linux.x86_64.zip
          unzip Godot_v$GODOT_VERSION-stable_linux.x86_64.zip
          mv Godot_v$GODOT_VERSION-stable_linux.x86_64 /usr/local/bin/godot
          rm Godot_v$GODOT_VERSION-stable_linux.x86_64.zip
          godot --version

      - name: Setup Export Templates
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          curl -LO https://github.com/godotengine/godot/releases/download/$GODOT_VERSION-stable/Godot_v$GODOT_VERSION-stable_export_templates.tpz
          mkdir -v -p ~/.local/share/godot/export_templates
          unzip Godot_v$GODOT_VERSION-stable_export_templates.tpz
          rm Godot_v$GODOT_VERSION-stable_export_templates.tpz
          mv templates ~/.local/share/godot/export_templates/$GODOT_VERSION.stable

      - name: Check version
        run: |
          if [ ! -f version.txt ]; then
            git config --global --add safe.directory $(pwd)
            git rev-list -P --count HEAD > version.txt
          fi
          echo BUILD $(cat version.txt)

      - name: Export
        id: export
        env:
          ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          EXPORT_TYPE_INPUT: ${{ github.event.inputs.exporttype }}
        if: env.ITCHIO_USERNAME && env.ITCHIO_GAME && env.BUTLER_API_KEY
        run: |
          EXPORT_TYPE="${EXPORT_TYPE_INPUT:=debug}"
          echo export $EXPORT_TYPE
          godot --headless --path . --export-${EXPORT_TYPE} "Web" exports/web/index.html
          godot --headless --path . --export-${EXPORT_TYPE} "Linux" exports/linux/${ITCHIO_GAME}.x86_64
          godot --headless --path . --export-${EXPORT_TYPE} "macOS" exports/macos/${ITCHIO_GAME}.zip
          godot --headless --path . --export-${EXPORT_TYPE} "Windows" exports/windows/${ITCHIO_GAME}.exe
          #find exports -name '*'

      - name: Cache butler files
        id: cache-butler
        if: steps.export.outcome == 'success'
        uses: actions/cache@v4
        with:
          path: butler
          key: ${{ runner.os }}-butler

      - name: Download Butler
        env:
          ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: steps.cache-butler.outputs.cache-hit != 'true' && steps.export.outcome == 'success'
        run: |
          wget -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Butler Push
        env:
          ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: steps.export.outcome == 'success' && env.ITCHIO_USERNAME && env.ITCHIO_GAME && env.BUTLER_API_KEY
        run: |
          if [ -f exports/web/index.html ]; then
            ./butler push exports/web/ ${ITCHIO_USERNAME}/${ITCHIO_GAME}:HTML5
          fi
          if [ -f exports/linux/${ITCHIO_GAME}.x86_64 ]; then
            ./butler push exports/linux/ ${ITCHIO_USERNAME}/${ITCHIO_GAME}:linux
          fi
          if [ -f exports/macos/${ITCHIO_GAME}.zip ]; then
            ./butler push exports/macos/ ${ITCHIO_USERNAME}/${ITCHIO_GAME}:macos
          fi
          if [ -f exports/windows/${ITCHIO_GAME}.exe ]; then
            ./butler push exports/windows/ ${ITCHIO_USERNAME}/${ITCHIO_GAME}:windows
          fi
