name: "godot-ci"
on: push

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: test-project
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  gut-tests:
    name: GUT Tests
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Test
        run: |
          pwd
          godot -d --headless --path . -s addons/gut/gut_cmdln.gd -gexit
